// App
export const APP_HANDLE_STATE = "APP_HANDLE_STATE";
export const APP_HANDLE_GLOBAL_STATE = "APP_HANDLE_GLOBAL_STATE";
export const FETCH_WEATHER = "FETCH_WEATHER";
export const FETCH_WEATHER_SUCCESS = "FETCH_WEATHER_SUCCESS";
export const DELETE_WEATHER = "DELETE_WEATHER";
